"""Add collaboration module tables

Revision ID: 3d7f6c506abd
Revises: 
Create Date: 2025-10-30 17:06:08.471127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7f6c506abd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_actor', 'activities', ['actor_id'], unique=False)
    op.create_index('idx_activities_project_created', 'activities', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_activities_type', 'activities', ['type'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('context_type', sa.String(length=16), nullable=False),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("context_type IN ('boq', 'task', 'project')", name='check_context_type'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_author', 'comments', ['author_id'], unique=False)
    op.create_index('idx_comments_created', 'comments', ['created_at'], unique=False)
    op.create_index('idx_comments_project_context', 'comments', ['project_id', 'context_type', 'context_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('project_collaborators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='check_role'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collab_project', 'project_collaborators', ['project_id'], unique=False)
    op.create_index('idx_collab_project_user', 'project_collaborators', ['project_id', 'user_id'], unique=True)
    op.create_index('idx_collab_user', 'project_collaborators', ['user_id'], unique=False)
    op.create_table('project_invitations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('editor', 'viewer')", name='check_invite_role'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'revoked', 'expired')", name='check_status'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invites_email', 'project_invitations', ['email'], unique=False)
    op.create_index('idx_invites_project', 'project_invitations', ['project_id'], unique=False)
    op.create_index('idx_invites_status', 'project_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_project_invitations_token_hash'), 'project_invitations', ['token_hash'], unique=True)
    op.add_column('boq_items', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('boq_items', sa.Column('total_price', sa.Float(), nullable=True))

    # SQLite doesn't support DROP COLUMN - skip for now (columns will remain)
    # op.drop_column('projects', 'description')
    # op.drop_column('projects', 'status')

    # SQLite doesn't support ALTER COLUMN TYPE - skip for now
    # op.alter_column('supplier_price_items', 'price',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Float(),
    #            existing_nullable=False)

    op.add_column('users', sa.Column('last_verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_sent_at')

    # SQLite doesn't support ALTER COLUMN TYPE - skip for now
    # op.alter_column('supplier_price_items', 'price',
    #            existing_type=sa.Float(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)

    # SQLite doesn't support ADD COLUMN with defaults properly - skip for now
    # op.add_column('projects', sa.Column('status', sa.TEXT(), server_default=sa.text("'ACTIVE'"), nullable=True))
    # op.add_column('projects', sa.Column('description', sa.TEXT(), nullable=True))

    op.drop_column('boq_items', 'total_price')
    op.drop_column('boq_items', 'unit_price')
    op.drop_index(op.f('ix_project_invitations_token_hash'), table_name='project_invitations')
    op.drop_index('idx_invites_status', table_name='project_invitations')
    op.drop_index('idx_invites_project', table_name='project_invitations')
    op.drop_index('idx_invites_email', table_name='project_invitations')
    op.drop_table('project_invitations')
    op.drop_index('idx_collab_user', table_name='project_collaborators')
    op.drop_index('idx_collab_project_user', table_name='project_collaborators')
    op.drop_index('idx_collab_project', table_name='project_collaborators')
    op.drop_table('project_collaborators')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_index('idx_notifications_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_comments_project_context', table_name='comments')
    op.drop_index('idx_comments_created', table_name='comments')
    op.drop_index('idx_comments_author', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_activities_type', table_name='activities')
    op.drop_index('idx_activities_project_created', table_name='activities')
    op.drop_index('idx_activities_actor', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
