"""Add tasks/PM module tables

Revision ID: 47df200fd252
Revises: 3d7f6c506abd
Create Date: 2025-10-30 20:44:37.133770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47df200fd252'
down_revision: Union[str, None] = '3d7f6c506abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=True),
    sa.Column('linked_resource_type', sa.String(length=24), nullable=True),
    sa.Column('linked_resource_id', sa.String(), nullable=True),
    sa.Column('boq_item_id', sa.String(), nullable=True),
    # SQLite doesn't support ARRAY - use TEXT to store JSON array
    sa.Column('labels', sa.Text(), nullable=True),  # Will store as JSON string
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assignee', 'tasks', ['assignee_id'], unique=False)
    op.create_index('idx_tasks_created_by', 'tasks', ['created_by'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('task_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_attach_task', 'task_attachments', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('depends_on_task_id', sa.BigInteger(), nullable=False),
    sa.Column('dependency_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("dependency_type IN ('blocks', 'blocked_by', 'relates_to')", name='check_dep_type'),
    sa.CheckConstraint('task_id != depends_on_task_id', name='check_no_self_dep'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_deps_depends', 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index('idx_task_deps_task', 'task_dependencies', ['task_id'], unique=False)
    op.create_table('task_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_rev_created', 'task_revisions', ['created_at'], unique=False)
    op.create_index('idx_task_rev_project', 'task_revisions', ['project_id'], unique=False)
    op.create_index('idx_task_rev_task', 'task_revisions', ['task_id'], unique=False)

    # SQLite doesn't support ALTER COLUMN TYPE - skip
    # op.alter_column('supplier_price_items', 'price',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Float(),
    #            existing_nullable=False)

    # This column was already added in previous migration - skip
    # op.add_column('users', sa.Column('last_verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Skip - already handled in previous migration
    # op.drop_column('users', 'last_verification_sent_at')

    # SQLite doesn't support ALTER COLUMN TYPE - skip
    # op.alter_column('supplier_price_items', 'price',
    #            existing_type=sa.Float(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)
    op.drop_index('idx_task_rev_task', table_name='task_revisions')
    op.drop_index('idx_task_rev_project', table_name='task_revisions')
    op.drop_index('idx_task_rev_created', table_name='task_revisions')
    op.drop_table('task_revisions')
    op.drop_index('idx_task_deps_task', table_name='task_dependencies')
    op.drop_index('idx_task_deps_depends', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('idx_task_attach_task', table_name='task_attachments')
    op.drop_table('task_attachments')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_created_by', table_name='tasks')
    op.drop_index('idx_tasks_assignee', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
