"""Add last_verification_sent_at to users

Revision ID: 84e43fc57b81
Revises: c0a224d53ec1
Create Date: 2025-11-03 20:21:56.191678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e43fc57b81'
down_revision: Union[str, None] = 'c0a224d53ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the missing column - SQLite doesn't support ALTER COLUMN
    op.add_column('users', sa.Column('last_verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_sent_at')
    # ### end Alembic commands ###
